name: swiftlint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - "*"

jobs:
  swiftlint:
    runs-on: macos-13
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v4
    - name: Switch Xcode 🔄
      run: sudo xcode-select --switch /Applications/Xcode_15.0.app
    - name: Swift Lint 🧹
      run: swiftlint --strict
